/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedCoursesSlugRouteImport } from './routes/_authenticated/courses.$slug'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin.users.index'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated/admin.courses.index'
import { Route as AuthenticatedAdminBundlesIndexRouteImport } from './routes/_authenticated/admin.bundles.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksGrowRouteImport } from './routes/api/public/webhooks/grow'
import { Route as AuthenticatedAdminUsersIdRouteImport } from './routes/_authenticated/admin.users.$id'
import { Route as AuthenticatedAdminCoursesNewRouteImport } from './routes/_authenticated/admin.courses.new'
import { Route as AuthenticatedAdminCoursesIdRouteImport } from './routes/_authenticated/admin.courses.$id'
import { Route as AuthenticatedAdminBundlesNewRouteImport } from './routes/_authenticated/admin.bundles.new'
import { Route as AuthenticatedAdminBundlesIdRouteImport } from './routes/_authenticated/admin.bundles.$id'
import { Route as AuthenticatedAdminCoursesIdIndexRouteImport } from './routes/_authenticated/admin.courses.$id.index'
import { Route as AuthenticatedAdminCoursesIdLessonsNewRouteImport } from './routes/_authenticated/admin.courses.$id.lessons.new'
import { Route as AuthenticatedAdminCoursesIdLessonsLessonIdRouteImport } from './routes/_authenticated/admin.courses.$id.lessons.$lessonId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedCoursesSlugRoute =
  AuthenticatedCoursesSlugRouteImport.update({
    id: '/courses/$slug',
    path: '/courses/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBundlesIndexRoute =
  AuthenticatedAdminBundlesIndexRouteImport.update({
    id: '/bundles/',
    path: '/bundles/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksGrowRoute = ApiPublicWebhooksGrowRouteImport.update({
  id: '/api/public/webhooks/grow',
  path: '/api/public/webhooks/grow',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersIdRoute =
  AuthenticatedAdminUsersIdRouteImport.update({
    id: '/users/$id',
    path: '/users/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesNewRoute =
  AuthenticatedAdminCoursesNewRouteImport.update({
    id: '/courses/new',
    path: '/courses/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesIdRoute =
  AuthenticatedAdminCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBundlesNewRoute =
  AuthenticatedAdminBundlesNewRouteImport.update({
    id: '/bundles/new',
    path: '/bundles/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBundlesIdRoute =
  AuthenticatedAdminBundlesIdRouteImport.update({
    id: '/bundles/$id',
    path: '/bundles/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesIdIndexRoute =
  AuthenticatedAdminCoursesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCoursesIdRoute,
  } as any)
const AuthenticatedAdminCoursesIdLessonsNewRoute =
  AuthenticatedAdminCoursesIdLessonsNewRouteImport.update({
    id: '/lessons/new',
    path: '/lessons/new',
    getParentRoute: () => AuthenticatedAdminCoursesIdRoute,
  } as any)
const AuthenticatedAdminCoursesIdLessonsLessonIdRoute =
  AuthenticatedAdminCoursesIdLessonsLessonIdRouteImport.update({
    id: '/lessons/$lessonId',
    path: '/lessons/$lessonId',
    getParentRoute: () => AuthenticatedAdminCoursesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/bundles/$id': typeof AuthenticatedAdminBundlesIdRoute
  '/admin/bundles/new': typeof AuthenticatedAdminBundlesNewRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRouteWithChildren
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/public/webhooks/grow': typeof ApiPublicWebhooksGrowRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/bundles/': typeof AuthenticatedAdminBundlesIndexRoute
  '/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/courses/$id/': typeof AuthenticatedAdminCoursesIdIndexRoute
  '/admin/courses/$id/lessons/$lessonId': typeof AuthenticatedAdminCoursesIdLessonsLessonIdRoute
  '/admin/courses/$id/lessons/new': typeof AuthenticatedAdminCoursesIdLessonsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/bundles/$id': typeof AuthenticatedAdminBundlesIdRoute
  '/admin/bundles/new': typeof AuthenticatedAdminBundlesNewRoute
  '/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/public/webhooks/grow': typeof ApiPublicWebhooksGrowRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/bundles': typeof AuthenticatedAdminBundlesIndexRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/admin/courses/$id': typeof AuthenticatedAdminCoursesIdIndexRoute
  '/admin/courses/$id/lessons/$lessonId': typeof AuthenticatedAdminCoursesIdLessonsLessonIdRoute
  '/admin/courses/$id/lessons/new': typeof AuthenticatedAdminCoursesIdLessonsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/bundles/$id': typeof AuthenticatedAdminBundlesIdRoute
  '/_authenticated/admin/bundles/new': typeof AuthenticatedAdminBundlesNewRoute
  '/_authenticated/admin/courses/$id': typeof AuthenticatedAdminCoursesIdRouteWithChildren
  '/_authenticated/admin/courses/new': typeof AuthenticatedAdminCoursesNewRoute
  '/_authenticated/admin/users/$id': typeof AuthenticatedAdminUsersIdRoute
  '/api/public/webhooks/grow': typeof ApiPublicWebhooksGrowRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/bundles/': typeof AuthenticatedAdminBundlesIndexRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/admin/courses/$id/': typeof AuthenticatedAdminCoursesIdIndexRoute
  '/_authenticated/admin/courses/$id/lessons/$lessonId': typeof AuthenticatedAdminCoursesIdLessonsLessonIdRoute
  '/_authenticated/admin/courses/$id/lessons/new': typeof AuthenticatedAdminCoursesIdLessonsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/payment-success'
    | '/privacy'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/admin/pricing'
    | '/courses/$slug'
    | '/admin/'
    | '/admin/bundles/$id'
    | '/admin/bundles/new'
    | '/admin/courses/$id'
    | '/admin/courses/new'
    | '/admin/users/$id'
    | '/api/public/webhooks/grow'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/bundles/'
    | '/admin/courses/'
    | '/admin/users/'
    | '/admin/courses/$id/'
    | '/admin/courses/$id/lessons/$lessonId'
    | '/admin/courses/$id/lessons/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/auth'
    | '/payment-success'
    | '/privacy'
    | '/reset-password'
    | '/dashboard'
    | '/admin/pricing'
    | '/courses/$slug'
    | '/admin'
    | '/admin/bundles/$id'
    | '/admin/bundles/new'
    | '/admin/courses/new'
    | '/admin/users/$id'
    | '/api/public/webhooks/grow'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/admin/bundles'
    | '/admin/courses'
    | '/admin/users'
    | '/admin/courses/$id'
    | '/admin/courses/$id/lessons/$lessonId'
    | '/admin/courses/$id/lessons/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accessibility'
    | '/auth'
    | '/payment-success'
    | '/privacy'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/courses/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/bundles/$id'
    | '/_authenticated/admin/bundles/new'
    | '/_authenticated/admin/courses/$id'
    | '/_authenticated/admin/courses/new'
    | '/_authenticated/admin/users/$id'
    | '/api/public/webhooks/grow'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/bundles/'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/admin/courses/$id/'
    | '/_authenticated/admin/courses/$id/lessons/$lessonId'
    | '/_authenticated/admin/courses/$id/lessons/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccessibilityRoute: typeof AccessibilityRoute
  AuthRoute: typeof AuthRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicWebhooksGrowRoute: typeof ApiPublicWebhooksGrowRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/courses/$slug': {
      id: '/_authenticated/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AuthenticatedCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bundles/': {
      id: '/_authenticated/admin/bundles/'
      path: '/bundles'
      fullPath: '/admin/bundles/'
      preLoaderRoute: typeof AuthenticatedAdminBundlesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/grow': {
      id: '/api/public/webhooks/grow'
      path: '/api/public/webhooks/grow'
      fullPath: '/api/public/webhooks/grow'
      preLoaderRoute: typeof ApiPublicWebhooksGrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users/$id': {
      id: '/_authenticated/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/new': {
      id: '/_authenticated/admin/courses/new'
      path: '/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AuthenticatedAdminCoursesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/$id': {
      id: '/_authenticated/admin/courses/$id'
      path: '/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bundles/new': {
      id: '/_authenticated/admin/bundles/new'
      path: '/bundles/new'
      fullPath: '/admin/bundles/new'
      preLoaderRoute: typeof AuthenticatedAdminBundlesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bundles/$id': {
      id: '/_authenticated/admin/bundles/$id'
      path: '/bundles/$id'
      fullPath: '/admin/bundles/$id'
      preLoaderRoute: typeof AuthenticatedAdminBundlesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses/$id/': {
      id: '/_authenticated/admin/courses/$id/'
      path: '/'
      fullPath: '/admin/courses/$id/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesIdRoute
    }
    '/_authenticated/admin/courses/$id/lessons/new': {
      id: '/_authenticated/admin/courses/$id/lessons/new'
      path: '/lessons/new'
      fullPath: '/admin/courses/$id/lessons/new'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdLessonsNewRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesIdRoute
    }
    '/_authenticated/admin/courses/$id/lessons/$lessonId': {
      id: '/_authenticated/admin/courses/$id/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/admin/courses/$id/lessons/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIdLessonsLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesIdRoute
    }
  }
}

interface AuthenticatedAdminCoursesIdRouteChildren {
  AuthenticatedAdminCoursesIdIndexRoute: typeof AuthenticatedAdminCoursesIdIndexRoute
  AuthenticatedAdminCoursesIdLessonsLessonIdRoute: typeof AuthenticatedAdminCoursesIdLessonsLessonIdRoute
  AuthenticatedAdminCoursesIdLessonsNewRoute: typeof AuthenticatedAdminCoursesIdLessonsNewRoute
}

const AuthenticatedAdminCoursesIdRouteChildren: AuthenticatedAdminCoursesIdRouteChildren =
  {
    AuthenticatedAdminCoursesIdIndexRoute:
      AuthenticatedAdminCoursesIdIndexRoute,
    AuthenticatedAdminCoursesIdLessonsLessonIdRoute:
      AuthenticatedAdminCoursesIdLessonsLessonIdRoute,
    AuthenticatedAdminCoursesIdLessonsNewRoute:
      AuthenticatedAdminCoursesIdLessonsNewRoute,
  }

const AuthenticatedAdminCoursesIdRouteWithChildren =
  AuthenticatedAdminCoursesIdRoute._addFileChildren(
    AuthenticatedAdminCoursesIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBundlesIdRoute: typeof AuthenticatedAdminBundlesIdRoute
  AuthenticatedAdminBundlesNewRoute: typeof AuthenticatedAdminBundlesNewRoute
  AuthenticatedAdminCoursesIdRoute: typeof AuthenticatedAdminCoursesIdRouteWithChildren
  AuthenticatedAdminCoursesNewRoute: typeof AuthenticatedAdminCoursesNewRoute
  AuthenticatedAdminUsersIdRoute: typeof AuthenticatedAdminUsersIdRoute
  AuthenticatedAdminBundlesIndexRoute: typeof AuthenticatedAdminBundlesIndexRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBundlesIdRoute: AuthenticatedAdminBundlesIdRoute,
  AuthenticatedAdminBundlesNewRoute: AuthenticatedAdminBundlesNewRoute,
  AuthenticatedAdminCoursesIdRoute:
    AuthenticatedAdminCoursesIdRouteWithChildren,
  AuthenticatedAdminCoursesNewRoute: AuthenticatedAdminCoursesNewRoute,
  AuthenticatedAdminUsersIdRoute: AuthenticatedAdminUsersIdRoute,
  AuthenticatedAdminBundlesIndexRoute: AuthenticatedAdminBundlesIndexRoute,
  AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCoursesSlugRoute: typeof AuthenticatedCoursesSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCoursesSlugRoute: AuthenticatedCoursesSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccessibilityRoute: AccessibilityRoute,
  AuthRoute: AuthRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicWebhooksGrowRoute: ApiPublicWebhooksGrowRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
